# 3 줄리아 기초

> **노트:** 쳅터에서 우리는 프로그래밍 언어로써 줄리아의 기초를 다룹니다. 이 쳅터는 도구로써 줄리아로 데이터 조작과 데이터 시각화에 반드시 필요한 부분이 아님을 알려드립니다. 줄리아에 대한 기초적인 이해가 있으면 줄리아를 사용할 때 분명 좀더 효과적이고 효율적이 됩니다. 하지만, 당신이 일단 시작하기 원한다면, 섹션 4로 넘어 가서 `DataFrames.jl`과 함께 테이블 데이터에 대해 배울 수 있습니다.

이 쳅터는 줄리아에 대한 아주 간략하고 깊지 않은 개괄이 될 것입니다. 이미 다른 프로그래밍 언어에 익숙하다며녀, 줄리아 문서(https://docs.julialang.org/)를 읽어보길 권해드립니다. 줄리아문서는 줄리아를 깊이 파볼 때 아주 훌륭한 자료입니다. 그 문서는 모든 기초와 코너 케이스를 커버합니다만, 좀 부담스러울 수 있습니다. 특히 당신이 소프트웨어 문서에 익숙하지 않으면 그럴겁니다.

우리는 줄리아의 기초만 다룰 것입니다. 줄리아를 새로운 테슬라 같은 팬시한 기능이 탑재된 차라고 상상해 보세요. 우리는 그저 어떻게 "차를 운전하고, 주차하고, 교통흐름 속에서 가야 하는지" 설명하는 수준입니다. 당신이 "핸들과 대시보드에 있는 모든 버튼"을 알고 싶다면, 이 자료는 적합하지 않습니다.

## 3.1 환경설정

언어 문법에 뛰어 들기 전에, 우리는 어떻게 코드를 돌리는지 알아야 합니다. 여러가지 다양한 옵션을 자세히 설명하는 것은 이 책의 범위를 넘어갑니다. 대신에, 우리는 여러 솔루션 중 몇가지 포인터를 제공할 것입니다.

가장 쉬운 방법은 줄리아 REPL을 사용하는 것입니다. 이 말은 줄리아 실행파일(`julia` 또는 `julia.exe`)로 시작해서 코드를 거기서 돌리는 겁니다. 예를 들면 우리는 REPL을 시작해서 몇 몇 코드를 돌릴 수 있습니다.

In [1]:
x = 2

2

In [2]:
x + 1

3

이 방식은 아주 잘 작동하지만, 당신이 우리가 적은 코드를 저장하고 싶다면? 저장하기 위해서 우리는 "script.jl"과 같은 ".jl"파일을 작성해야합니다.기록 이것을 줄리아로 불러와야 합니다. "script.jl"파일이 다음과 같은 코드를 가지고 있다고 해봅시다.

In [3]:
x = 3
y = 4

4

우리는 이것을 줄리아로 불러올 수 있습니다.

In [4]:
include("script.jl")
y

4

이제 문제는 우리가 줄리아를 시작할 때마다 우리의 코드 실행하기 전에 우리의 스크립트를 다시 읽어오게 하고 싶습니다. 이것은 Revise.jl을 사용해서 할 수 있습니다. 왜냐하면 줄리아 컴파일 시간이 때때로 길기 때문에, `Revise.jl`은 줄리아 개발에 필수적입니다.
더 많은 사항은, `Revise.jl` 문서나 구글에 당신의 구체적인 질문을 검색해 보세요.

우리는 `Revise.jl`과 REPL이 어늦어도 수작업을 필요로 한다는 것을 인지하고 있습니다. 그것은 깔끔하게 정리되지 않았습니다.
다행히도, Pluto.jl라는 것이 있습니다. `Pluto.jl`는 자동으로 의존성을 관리해주고, 코드를 실행시키고, 변화를 **반영**해 줍니다. 새롭게 프로그램을 시작하는 사람들에게, `Pluto.jl`은 가장 쉽게 시작하는 방법입니다. 이 패키지의 가장 큰 한계점은 큰 프로젝트에 적합하지 않다는 점입니다.

또다른 옵션은 비쥬얼 스튜디오 코드에서 줄리아 확장을 하거나 당신만의 IDE에서 사용하는 것입니다. 만약 당신이 IDE가 뭔지 **모른지만** 큰 프로젝트 들을 관리하고 싶다면 VS Code를 고르세요. 당신이 IDE가 뭔지 **안다면**, 당신은 Vim이나 Emacs, REPL을 통해 자신만의 IDE를 구축할 것입니다.

요약하자면:

* 가장 쉬운 방법 -> `Pluto.jl`
* 큰 프로젝트 -> Visual Studio Code
* 고급 사용자 -> Vim, Emacs와 REPL

## 3.2 언어 문법

줄리아는 just-in-time 컴파일러가 있는 **동적 타입 언어**입니다. 이말은 여러분은 당신의 프로그램을 돌리기 전까지는 C++나 포트란 처럼 컴파일 할  필요가 없다는 뜻입니다. 
대신 줄리아는 당신의 코드를 가지고 필요한 곳에서 타입을 추론하고,실행되기 직전에 필요한 부분을 컴파일을 합니다. 또한, 명시적으로 각 타입을 선언할 필요가 없습니다. 줄리아는 실행되면서 당신을 위해 타입을 추론합니다.

R이나 파이썬 같은 동적 언어와 줄리아가 가장 큰 차이를 보이는 부분은 다음과 같습니다.
우선, 줄리아는 **유저가 타입 선언을 특정할 수 있도록 허락합니다.** 당신은 이미 왜 줄리아인가?(섹션[2]())에서 타입 선언을 보았습니다. 그것은 때 때로 변수 뒤에 붙은 이런 더블 콜론`::` 입니다. 
그러나 당신이 변수나 합수의 타입을 정의하고 싶지 않다면, 줄리아는 기쁘게 그들을 추론(추측)할 것입니다.

둘째로 줄리아는 멀티플 디스패치를 통해 많은 타입 조합에 대한 함수 행동을 정의할 수 있게 합니다. 우리는 이미 멀티플 디스패치에 대해서 섹션 [2.3]()에서 다루었습니다. 우리는 다른 타입행동을 같은 이름을 가진 다른 변수 타입응ㄹ 가진 함수를 새롭게 정의함으로 선언할 수 있었습니다. 

### 3.2.1 변수

변수는 특정 이름에 컴퓨터가 저장한 값을 알려줍니다. 그렇기 때문에 당신은 나중에 이 값을 찾아오거나 바꿀 수 있습니다. 줄리아는 여러 변수 타입이 있습니다만, 데이터과학에서는 우리는 대부분 다음과 같은 변수타입을 사용합니다.

* 정수형: `Int64`
* 실수형: `Float64`
* 불리언: `Bool`
* 문자열: `String`

정수형과 실수형은 64비트를 기본으로 저장됩니다. 그렇기 때문에 `64`라는 어미가 붙어 있습니다. 좀더 정교하거나 낮은 정밀도가 필요하다면 `Int8`이나 `Int128` 타입이 있습니다. 더 높은 수는 더 나은 정밀도를 의미합니다. 대부분의 경우 이것은 문제가 되지 않기 때문에 기본 정밀도를 사용하면 됩니다.

우리는 왼쪽에 변수명을 두고 오른쪽에 값을 두고 가운데에 할당연산자인`=`를 써서 변수를 만들 수 있습니다. 예를 들어

In [5]:
name = "Julia"
age = 9

9

한가지 언급하자면, 마지막 선언문(`age`)이 콘솔에 출력 되었습니다. 여게서 우리는 두 변수`name`과 `age`를 정의하고 있습니다. 우리는 이 변수의 이름을 적음으로 그들에게 할당된 값을 가져 올 수 있습니다.

In [6]:
name

"Julia"

만약 당신이 새로운 값을 이미 존재하는 변수에 정의하고 싶다면, 당ㅇ신은 할당하는 단계를 반복 할 수 있습니다. 그러면 줄리아는 이전 값을 새로운 값으로 덮어 씌울 것입니다. 가령, 줄리아의 생일이 지나서 이제 10살이 되었다면:

In [7]:
age = 10

10

같은 활동을 `name`에서도 할 수 있습니다. 가령 줄리아가 이 놀라운 속도로 인해서 몇몇 칭호를 얻었다고 해봅시다. 우리는 변수 `name`을 새로운 값으로 바꿀 것입니다.

In [8]:
name = "Julia Rapidus"

"Julia Rapidus"

우리는 또한 변수간 더하기나 나누기 연산을 할 수 있습니다. 줄리아가 몇개월인지 12를 곱해서 알아봅시다.

In [9]:
12*age

120

우리는 `typeof`함수를 써서 변수의 타입을 알아낼 수 있습니다.

In [10]:
typeof(age)

Int64

다음 질문은 "정수형으로 나는 무엇들을 할 수 있지?"가 될 겁니다. 여기에 아주 편리한 `methodswith`라는 함수가 있습니다. 이 함수는 어떤 타입이 사용가능한 모든 함수를 보여줍니다. 여기서 나는 첫 5개만 보이도록 제한했습니다.

In [11]:
first(methodswith(Int64), 5)

[1] middle(x::Union{Bool, Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8}) in Statistics at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Statistics/src/Statistics.jl:735
[2] tofirst(dt::Dates.TimeType, dow::Int64; of) in Dates at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Dates/src/adjusters.jl:379
[3] tolast(dt::Dates.TimeType, dow::Int64; of) in Dates at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Dates/src/adjusters.jl:391
[4] tonext(dt::Dates.TimeType, dow::Int64; same) in Dates at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Dates/src/adjusters.jl:338
[5] toprev(dt::Dates.TimeType, dow::Int64; same) in Dates at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Dates/src/adjusters.jl:359

### 3.2.2 사용자 정의 타입

여러 변수들을 게측이나 관계 없이 가지고 있는 것은 이상적이지 못합니다. 줄리아에서, 우리는 그렇게 구조화된 데이터를 `struct`(또다른 이름으로는 복합타입)을 통해 정의할 수 있습니다. 각`struct` 안에서 당신은 여러 필드를 지정할 수 있습니다. 이것들은 줄리아 코어에 정의된 원시 타입(예시: 정수형, 실수형)과 다릅니다. 대부분의 `struct`은 사용자가 정의하기 때문에, 그들은 사용자 정의 타입이라고 합니다.

예를 들어, 과학적 오픈소스 프로그래밍 언어를 나타낼`struct`을 만든다고 합시다. 우리는 또한 필요한 타입들을 `struct`안에 정의할 것입니다.

In [12]:
struct Language
    name::String
    title::String
    year_of_birth::Int64
    fast::Bool
end

당신이 상요할 수 있는 필드 이름을 알기 위해서 `fieldnames`라는 함수에 알고자 하는 `struct`를 집어넣으면 됩니다.

In [13]:
fieldnames(Language)

(:name, :title, :year_of_birth, :fast)

`struct`를 사용하기 위해서, 우리는 각 `struct`에서 정의한 필드 값을 가지고 개별 인스턴스(또는 "객체")를 생성해야 합니다. 
파이썬에서와 줄리아 두 객체를 생성해 봅시다.

In [14]:
julia = Language("Julia", "Rapidus", 2012, true)
python = Language("Python", "Letargicus", 1991, false)

Language("Python", "Letargicus", 1991, false)

한가지 `struct`에 대해 언급할 부분은 우리는 한번 생성한 후 값을 바꿀 수 없다는 점입니다. 이 문제는 `mutable struct`을 통해서 해결 할 수 있습니다. 또한, 가변 객체는 일반적으로 느리고 좀더 에러에 취약합니다. 가능하다면, 모든 것을 *불변*으로 만드십시오. 그러면 `mutable struct`을 만들어 봅시다.

In [15]:
mutable struct MutableLanguage
    name::String
    title::String
    year_of_birth::Int64
    fast::Bool
end

julia_mutable = MutableLanguage("Julia", "Rapidus", 2012, true)

MutableLanguage("Julia", "Rapidus", 2012, true)

우리가 `julia_mutable`의 타이틀을 바꾸고 싶다고 해봅시다. `julia_mutable`이 `mutable struct`으로 생성되었기 때문에 이제 우리는 바꿀 수 있습니다.

In [16]:
julia_mutable.title = "Python Obliteratus"

julia_mutable

MutableLanguage("Julia", "Python Obliteratus", 2012, true)

### 3.2.3 불리언 연산자와 수치 비교

이제 타입을 커버했기 때문에, 우리는 불리언 연산자와 수치 비교로 이동할 수 있습니다.

줄리아에서는 세가지 불리언 연산자가 있습니다.

- `!`: **NOT**
- `&&` : **AND**
- `||` : **OR**

여기 몇가지 예시가 있습니다.

In [17]:
!true

false

In [18]:
(false&&true) || (!false)

true

In [19]:
(6 isa Int64) && (6 isa Real)

true

수치 비교에 있어서, 줄리아는 세가지 주요한 비교 타입이 있습니다.

1. **동격**: 어떤 것이 같거나 같지 않을 것
  - =="equal"
  - != 또는 ≠"not equal"
2. **보다 작은**: 어떤 것이 작거나 같을 때
  - < "작거나"
  - <= 또는 ≤ "작거나 같은"
3. **보다 큰**: 어떤 것이 크거나 같을 때
  - > "크거나"
  - >= 또는 ≥ "크거나 같을 때
  
 여기 몇가지 예시가 있다

In [20]:
1 == 1

true

In [21]:
1 >= 10

false

이것은 다른 타입 간에도 작동한다.

In [22]:
1 == 1.0

true

우리는 불리언 연산과 수치 비교를 섞어서 쓸 수 있다.

In [23]:
(1 != 10) || (3.14 <= 2.71)

true

### 3.2.4 함수

이제 우리는 변수와 `struct`을 통해 임의 타입을 정의할 수 있습니다. 이제 우리의 관심을 **함수**로 돌려봅시다. 줄리아에서, 함수는 **함수인자의 값을 하나나 더 많은 리턴 값들로 맵핑합니다.** 기초적인 문법은 다음과 같습니다:

```julia
function function_name(arg1, arg2)
    result = stuff with the arg1 and arg2
    return result
end
```

함수 선언은 키워드 `function`과 함수명으로 시작합니다. 그리고 괄호`()`안에 콤마`,`를 사용해 함수인자를 구분하여 정의합니다. 함수 안에서 우리가 집어 넣은 파라미터를 가지고 줄리아가 무엇을 하길 원하는지를 구체화 합니다. 우리가 함수 안에서 정의한 모든 변수는 함수값이 반환되면서 지워집니다. 이것은 마치 자동 청소와 같은 것으로 좋은 점입니다. 함수 본문에서의 모든 연산이 끝나고 나면, 우리는 줄리아에게 `return` 선언을 통해 최종결과를 반환하도록 합니다. 마지막으로, 우리는 `end` 키워드를 통해 줄리아가 함수 정의가 긑났음을 알려줍니다. 

컴팩트한 **할당 폼**이 존재합니다.

```f_name(arg1, arg2) = stuff with arg1 and arg2```

이 함수는 우리가 위에서 정의한 함수와 **같은 함수**입니다만, 좀더 컴팩트한 형태를 취하고 있습니다. 최우선 되는 규칙은 당신의 코드가 92문자 내로 쉽게 들어갈 수 있으면 컴팩트한 형태가 적당합니다. 그렇지 않다면 우리는 `function`키워드를 쓰는 긴 형태를 사용합니다. 예시를 보면서 이어갑시다.

#### 3.2.4.1 새로운 함수 만들기

숫자를 더하는 새로운 함수를 만들어 봅시다.

In [24]:
function add_numbers(x, y)
    return x + y
end

add_numbers (generic function with 1 method)

이제 우리는 우리가 만든 `add_numbers`함수를 사용할 수 있습니다.

In [25]:
add_numbers(17, 29)

46

그리고 이것은 floats형에서도 작동합니다.

In [26]:
add_numbers(3.14, 2.72)

5.86

또한 우리는 타입 선언을 통해 임의의 행동을 정의할 수 있습니다. 우리가 `round_number` 함수를 만들면서 입력값이 `Float64`인지 `Int64`인지에 따라 다르게 행동하길 바란다고 합시다.

In [27]:
function round_number(x::Float64)
    return round(x)
end

function round_number(x::Int64)
    return x
end

round_number (generic function with 2 methods)

우리는 여러 메소드가 있는 함수임을 볼 수 있습니다.

In [28]:
methods(round_number)

# 2 methods for generic function "round_number":
[1] round_number(x::Float64) in Main at In[27]:1
[2] round_number(x::Int64) in Main at In[27]:5

여기에 한가지 이슈가 있습니다. 만약에 우리가 32비트 실수형인 `Float32`를 반올림 하고 싶다면 아니면 8비트 정수형인 `Int8`이라면?

당신이 모든 정수와 실수 타입에 대한 함수를 원한다면, 당신은 `AbstractFloat`이나 `Integer`와 같은 **추상타입(abstract type)**을 타입 시그니쳐에 넣으면 됩니다. 

In [29]:
function round_number(x::AbstractFloat)
    return round(x)
end

round_number (generic function with 3 methods)

이제, 이것은 모든 실수형에 대해 작동될 것입니다.

In [30]:
x_32 = Float32(1.1)
round_number(x_32)

1.0f0

> **노트:** 우리는 `supertypes`와 `subtypes` 함수로 타입들을 조사할 수 있습니다.

앞서 우리가 정의한 `Language` `struct`로 돌아가봅시다.
이 예제는 멀티플 디스패치에 대한 예제 입니다.
우리는 `Base.show` 함수가 확장하여 이스턴스 타입과 `struct`들을 출력하도록 할 겁니다.

기본적으로, 위에서 본 파이썬 케이스와 같이 `struct`은 기본 출력이 있습니다. 우리는 새로운 `Base.show`메소드를 정의해서 프로그래밍 언어 인스턴스의 출력이 좀더 낫게 할 수 있습니다. 우리는 프로그래밍 언어 이름과, 타이틀, 연도들을 확실하에 보여주길 원합니다. `Base.show`는 `IO`type을 인자로 받으며, 당신이 원하는 임의의 행동을 할 타입을 이어 적습니다.

In [31]:
Base.show(io::IO, l::Language) = print(
    io, l.name, ", ", 
    2021 - l.year_of_birth, "years old, ", 
    "has the follwoing titles: ", l.title
    )

이제 `python`이 어떻게 아웃풋이 보이는지 봅시다.

In [32]:
python

Python, 30years old, has the follwoing titles: Letargicus

#### 3.2.4.2 복수 반환 값

암수는 두개나 더 많은 값을 반환할 수 있습니다. 아래에 있는`add_multiply`라는 새 함수를 를 봐주세요.

In [33]:
function add_multiply(x, y)
    addition = x+y
    multiplication = x*y
    return addition, multiplication
end

add_multiply (generic function with 1 method)

이 경우 우리는 두가지 일을 할 수 있습니다.

1. 우리는, 유사하게 두 반환값을 두 변수가 함수의 변환 값을 갖도록 각각 저장할 수 있습니다.

In [34]:
return_1, return_2 = add_multiply(1, 2)
return_2

2

또는 우리는 한 변수가 함수의 반환 값을 갖게 하며 `first`나 `last`를 통해 접근할 수 있습니다.

In [35]:
all_returns = add_multiply(1, 2)
last(all_returns)

2

#### 3.2.4.3 키워드 인자

어떤 함수들은 위치로 인자를 받지 않고 키워드로 인자를 받을 수 있습니다. 이런 인자들은 일반적인 인자처럼 정의할 수 있습니다. 단, 정규인자 뒤 세미콜론`;`으로 구분해서 정의됩니다. 예를 들어, `logarithm` 함수를 정의한다고 합시다. 기본 값으로 자연로그 $e$(2.718281828459045)를 밑으로 키워드 인자로 받습니다. 여기서 강조하고 싶은 것은 우리는 추상 타입인 `Real`을 사용해서 `Real`의 하위 타입인`Integer`와 `AbstractFloat`에서 사용되는 모든 타입을 커버한다는 점입니다.

In [36]:
AbstractFloat <: Real && Integer <: Real

true

In [37]:
function logarithm(x::Real; base::Real=2.7182818284590)
    return log(base, x)
end

logarithm (generic function with 1 method)

이 함수는 `base` 인자를 특정하지 않아도 기능합니다. 우리가 함수를 선언할 때`기본 인자 값`을 지정했기 때문입니다.

In [38]:
logarithm(10)

2.3025850929940845

그리고 또한 키워드 인자`base`를 기본 값과 다른 값으로 전달할 수 있습니다.

In [39]:
logarithm(10; base=2)

3.3219280948873626

#### 3.2.4.4 익명함수

때때로 우리는 함수의 이름은 별 신경 쓰지 않으면서 빨리 만드는 걸 원합니다. 그 때 필요한 것이 바로 **익명 함수(anonymous functions)**입니다. 그들은 줄리아 데이터 과학 워크플로우에서 많이 사용됩니다. 
예를들어 `DataFrames.jl`(섹션 [4]())이나 `Makie.jl`(섹션 [5]())를 사용할 때, 때때로 우리는 데이터를 필터링하거나 플롯 레이블 모양을 잡을 임시 함수가 필요합니다. 이것들은 우리가 함수를 만들지 않고 간단히 한 곳에서 사용될 때 특히 유용합니다.

문법은 단순합니다. 우리는 `->`연산자를 사용합니다. `->`의 왼쪽에는 파라미터 이름이 들어가고, 오른쪽에는 파라미터로 하고자 하는 연산이 정의됩니다. 여기 예시가 있습니다. 지수를 사용하여 로그 변환한 것을 되돌린다고 생각해 봅시다.

In [40]:
map(x->2.7182818284590^x, logarithm(2))

2.0

여기서, 우리는 `map`함수를 사용했습니다. `map` 함수는 편리하게 익명 함수를 `logarithm(2)`(두번째 인자)에 맵핑을 해줍니다. 그 결과 우리는 같은 수치를 갖게 되었습니다. 왜냐하면 로그와 지수는 역함수 관계에 있기 때문입니다.(최소한 우리가 밑을 2.718218284590으로 한다면 말입니다.)

### 3.2.5 조건문 IF-Else-Elseif

대부분의 프로그래밍 언어에서, 유저는 컴퓨터의 실행 순서를 조작할 수 있습니다. 상황에 따라서, 우리는 컴퓨터가 이것을 하거나 저것을 하길 원할 때가 있습니다. 줄리아에서 우리는 실행 순서를 `if`, `elseif`과 `else` 키워드를 사용해서 조작할 수 있습니다. 이런 것들을 조건문이라고 합니다.

`if` 키워드는 줄리아에게 다음 표현을 평가하게 하고 그 결과가 `true`인지 `false`인지에 따라 코드 덩어리를 실행시키도록 합니다. 우리는 몇가지 `if` 조건에`elseif`를 조압할 수 있습니다. 복잡한 순서도인 경우에 말입니다. 마지막을오 우리는 `if`나 `elseif`의 값이 `true`가 아닌 경우에 안쪽 코드를 실행하게 정의할 수 있습니다. 이를 위해 `else`키워드가 있습니다. 마지막으로 위에서 본 모든 키워드연산자와 같이 우리는 줄리아에게 조건문이 언제 끝나는지 `end`키워드를 써서 알려줘야 합니다.

여기 `if`-`elseif`-`else`키워드 예제가 있습니다.

In [41]:
a = 1
b = 2

if a < b 
    "a is less than b"
elseif  a > b
    "a is greater than b"
else
    "a is equal to b"
end

"a is less than b"

우리는`campare`라고 하는 함수로 감쌀 수 있습니다.

In [42]:
function compare(a, b)
    if a < b
        "a is less than b"
    elseif a > b
        "a is greater than b"
    else
        "a is equal to b"
    end
end

compare(3.14, 3.14)

"a is equal to b"

### 3.2.6 For 루프

클래식한 for루프는 조건문과 닮은 문법을 따라 키워드로 시작합니다. 이 경우에는 `for`로 시작합니다. 그리고 당신은 줄리아가 순환할 "루프" 또 다른 말로 시퀀스를 지정합니다. 또한 다른 것과 같이 `end`키워드로 끝내야 합니다. 

그러면, 줄리아가 1부터 10까지 모든 숫자를 출력하게 하기 위해 다음과 같은 루프를 사용할 수 있습니다.

In [43]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


### 3.2.7 while 순환문

While 순환문은 앞서 본 if문과 for 루프의 합성입니다. 여기서 루프는 매번 컨디션이 `true`일때 실행됩니다. 문버븐 이전 것고 ㅏ같은 형태입니다. 우리는 키워드 `while`로 시작하여 `true`나 `false`로 판명날 수 있는 조건을 평가합니다. 다른 때와 같이 `end` 키워드로 끝나야 합니다.

여기 예시가 있습니다.

In [44]:
n = 0

while n < 3
    global n += 1
end

n

3

보다시피 우리는 `global` 키워드를 사용해야 합니다. 이것은 **변수 범위** 때문입니다. 조건문, 로프 그리고 함수 안에서 정의된 변수는 그 안에서만 존재합니다. 

여기서 우리는 줄리아에게 `while`루프 안에 있는 `n`은 전역변수라는 것을 `global` 키워드를 통해 알려줘야 합니다.

마지막으로, 우리는 또한 `+=`연산자를 사용했습니다. 이것은 `n = n+1`의 축약형힙니다.

## 3.3 네이티브 데이터 구조

줄리아는 몇가지 네이티브 데이터 구조를 가지고 있습니다. 그들은 구조화된 데이터의 형식을 나타내는 데이터 추상형입니다. 우리는 가장 많이 사용되는 것들만 다룰 거십니다. 그들은 일관되거나 다양한 형태의 데이터를 보관합니다. 그들이 collections이라면, 그들은 `for` 루프를 통해 순환할 수 있습니다. 

우리는 `String`, `Tuple`, `NamedTuple`, `unitRange`, `Array`, `Pair`, `Dict`, `Symbol`을 다룰 예정입니다.

당신이 줄리아 데이터 구조에 어려움을 겪고 있다면 당신은 `methodswith`라는 함수로 메소드를 찾을 수 있습니다. 줄리아에서 함수와 메소드의 차이는 다음과 가티 구분됩니다. 모든 함수는 우리가 이전에 보인 것과 같이 복수의 메소드를 가질 수 있습니다. `methodswith`함수는 당신이 알아둘만한 트릭입니다. 그렇다면 우리가 `String`으로 무엇을 할 수 있는지 알아봅시다.

In [45]:
first(methodswith(String), 5)

[1] vparse(s_::String) in VersionParsing at /root/.julia/packages/VersionParsing/YFVo1/src/VersionParsing.jl:39
[2] artifact_hash(name::String, artifacts_toml::String; platform, pkg_uuid) in Artifacts at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Artifacts/src/Artifacts.jl:419
[3] artifact_meta(name::String, artifacts_toml::String; platform, pkg_uuid) in Artifacts at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Artifacts/src/Artifacts.jl:366
[4] artifact_meta(name::String, artifact_dict::Dict, artifacts_toml::String; platform) in Artifacts at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Artifacts/src/Artifacts.jl:378
[5] find_artifacts_toml(path::String) in Artifacts at /opt/julia-1.6.4/share/julia/stdlib/v1.6/Artifacts/src/Artifacts.jl:484

### 3.3.1 연산과 함수 뿌리기(Broadcasting)

우리가 데이터 구조에 더 깊이 들어가기 전에, 우리는 브로드캐스팅(또 다른 이름으로는 벡터라이징)과 닷 연산자`.` 에 대해 이야기 하고자 합니다.

우리는 `*`(곱셈), `+`(덧셈)과 같은 수학적 연산을 닷 연산자를 통해 뿌릴 수 있습니다. 예를 들어, 덧셈을 흩뿌리는 건 `+`을 `.+`로 바굼을 통해 할 수 있습니다. 

In [46]:
[1, 2, 3] .+ 1

3-element Vector{Int64}:
 2
 3
 4

이는 또한 함수에도 자동 적용 됩니다.(기술적으로 수학연산이나, 고정 연산자(infix operator) 는 또한 함수입니다만, 그렇게 중요하지 않습니다.) `logarithm`함수를 기억하시나요?

In [47]:
logarithm.([1, 2, 3])

3-element Vector{Float64}:
 0.0
 0.6931471805599569
 1.0986122886681282

#### 3.3.1.1 뱅(!)이 있는 함수

줄리아 규약중 하나로 함수 이름에 뱅`!`이 있는 경우 하나 이상의 인자를 바꾸는 것을 의미합니다. 이 규약은 사용자에게 **순수함수**(이 함수는 부작용이 있음)가 아니라는 경고를 주기 위함입니다. 부작용이 있는 함수는 당신이 큰 데이터 구조를 업데이트 하거나 새로운 변수 컨테이너를 오버헤드 없이 생성할 때 유용합니다.

예를 들어, 우리는 벡터 `v`에 1씩 더하는 함수를 만들 수 있습니다.

In [48]:
function add_one!(V)
    for i in 1:length(V)
        V[i] += 1
    end
    return nothing
end

add_one! (generic function with 1 method)

In [49]:
my_data = [1, 2, 3]

add_one!(my_data)

my_data

3-element Vector{Int64}:
 2
 3
 4

### 3.3.2 문자열

**문자열(String)**은 쌍따옴표로 표현됩니다.

In [50]:
typeof("This is a string")

String

우리는 또한 여러 줄을 작성할 수 있습니다.

In [51]:
text = "
This is a big multiline string.
As you can see.
It is still a String to Julia.
"

"\nThis is a big multiline string.\nAs you can see.\nIt is still a String to Julia.\n"

하지만 보통 삼중 쌍따옴표를 사용해서 쓰는 것이 더 깔끔합니다.

In [52]:
S = """
    This is a big multiline string with a nested "quotation".
    As you can see.
    It is still a String to Julia
    """

"This is a big multiline string with a nested \"quotation\".\nAs you can see.\nIt is still a String to Julia\n"

삼중 쌍따옴표를 쓰는 경우, 들여쓰기와 시작할 때 줄바꾸기는 무시됩니다. 이는 코드 가독성을 높여줍니다. 왜냐하면 소스코드에서 블럭을 들여쓸 때 문자열에서의 이런 들여쓰기가 사라지기 때문이니다.

#### 3.3.2.1 문자열 병합

흔한 문자열 연산은 **문자열 병합**입니다. 두개나 그 이상의 문자열을 합쳐서 새로운 문자열을만들고 싶다면, 줄리아에서는 `*` 연산자나 `join`함수를 통해 달성할 수 있습니다. 이 심폴은 이상한 선택으로 들리고 실제로 그렇습니다. 지금은, 많은 줄리아 코드베이스가 이 연산자를 사용하기 때문에 이렇게 남을 것입니다. 좀더 관심이 있다면, 2015년부터 이어져온 토론을 읽어보세요. https://github.com/JuliaLang/julia/issues/11030.

In [53]:
hello = "Hello"
goodbye = "Goodbye"
hello * goodbye

"HelloGoodbye"

In [54]:
import Base.+


function +(a::String, b::String)
    return a*b
end

+ (generic function with 191 methods)

In [55]:
hello + goodbye

"HelloGoodbye"

보다시피, `hello`와 `goodbye`사이에 공백이 없습니다. 우리는 `" "` 문자열을 추가해서 `*`로 병합할 수도 있지만, 두개 이상의 문자열일 경우 귀찮습니다. 그런 경우가 `join`함수가 편리한 지점입니다. 우리는 그저 문자열을 대괄호`[]`에 넣고 구분자를 넘기면 됩니다.

In [56]:
join([hello, goodbye], " ")

"Hello Goodbye"

#### 3.3.2.2 문자열 삽입

문자열 병합은 때때로 복잡할 수 있습니다. 우리는 **문자열 삽입**을 이용해 좀더 나은 표현력을 가질 수 있습니다. 이것은 다음과 같이 진행됩니다.

당신은 `$` 달러 사인을 이용해 당신이 집어 넣고 싶은 뭐든 문자열에 집어 넣을 수 있습니다. 위와 동일하지만 삽입을 사용한 예시입니다.

In [57]:
"$hello $goodbye"

"Hello Goodbye"

이것은 함수 안에서도 작동합니다. 우리의 섹션 3.2.5의 `test`함수를 개선해 봅시다.

In [58]:
function test_interpolated(a, b)
    if a < b
        "$a is less than $b"
    elseif a > b
        "$a is greater than $b"
    else
        "$a is equal to $b"
    end
end

test_interpolated(3.14, 3.14)

"3.14 is equal to 3.14"

#### 3.3.2.3 문자열 조작

줄리아에서 문자열을 조작하는 여러가지 함수가 있습니다. 우리는 그중 가장 많이 사용하는 것을 보여드리고자 합니다. 또한, 대부분의 이 함수들은 [정규표현식]()을 인자로 받습니다. 우리는 정규표현식을 이 책에서 커버하지 않습니다만, 배우기를 권장합니다. 특히 당신이 텍스트 데이터를 주로 다룬다면요.

먼저 우리가 가지고 놀 문자열을 정의합니다.

In [59]:
julia_string = "Julia is an amazing open source programming language"

"Julia is an amazing open source programming language"

1. `contains`, `startswith`와 `endwith`: 조건문(`true`나 `false`를 반환)하는 것으로 두번째 인자는 :

- 첫번째 인자의 **일부(substring)**

In [60]:
contains(julia_string, "Julia")

true

- 첫번째 인자의 **접두어(prefix)**

In [61]:
startswith(julia_string, "Julia")

true

- 첫 번째 인자의 **어미(suffix)**

In [62]:
endswith(julia_string, "Julia")

false

2. `lowercase`, `uppercase`, `titlecase`와 `lowercasefirst`:

In [63]:
lowercase(julia_string)

"julia is an amazing open source programming language"

In [64]:
uppercase(julia_string)

"JULIA IS AN AMAZING OPEN SOURCE PROGRAMMING LANGUAGE"

In [65]:
titlecase(julia_string)

"Julia Is An Amazing Open Source Programming Language"

In [66]:
lowercasefirst(julia_string)

"julia is an amazing open source programming language"

3. `replace`: `Pair`라고 하는 새로운 문법을 소개합니다.

In [67]:
replace(julia_string, "amazing" => "awesome")

"Julia is an awesome open source programming language"

4. `split`: 구분자로 문자열을 쪼갭니다.

In [68]:
split(julia_string, " ")

8-element Vector{SubString{String}}:
 "Julia"
 "is"
 "an"
 "amazing"
 "open"
 "source"
 "programming"
 "language"

#### 3.3.2.4 문자열 변환

종종 우리는 타입간 **변환**을 해야 합니다.. 숫자를 문자로 변환하기 위해서 우리는 `string` 함수를 이용할 수 있습니다.

In [69]:
my_number = 123
typeof(string(my_number))

String

때때로, 우리는 반대로 문자열을 숫자로 바꾸어야 할 때도 있습니다. 줄리아는 `parse`라는 편리한 함수가 있어 이를 해낼 수 있습니다.

In [70]:
typeof(parse(Int64, "123"))

Int64

때로, 우리는 이런 변환을 안정적으로 하고 싶습니다. 그 때 `tryparse` 함수가 필요합니다. 이것은 `parse`와 기능은 동일하지만, 요청한 타입을 반환하거나 `nothing`을 반환합니다. 그렇기 때문에 `tryparse`는 우리가 에러를 피하고 싶을 때 유용합니다. 물론 이후에 `nothing`값을 처리해야 할 것입니다.

In [71]:
tryparse(Int64, "A very non-numeric string")

### 3.3.3 튜플

줄리아는 **튜플(Tuple)**이라는 데이터 구조를 가지고 있습니다. 그들은 줄리아에서 아주 특별한데, 왜냐하면 그들은 함수와 관련되어서 사용되기 때문입니다.
함수가 줄리아에서 중요한 기능이기 때문에, 모든 줄리아 유저는 튜플 기초를 알아야 합니다.

튜플은 **고정된 크기의 컨테이너로 여러 다른 타입의 값들을 가질 수 있습니다.** 튜플은 **불변 객체**로 이것은 생성(instantiation)되고 나면 수정할 수 없습니다. 튜플을 만들기 위해, 괄호`()`를 시작과 끝에 붙이며, 값들 사이에는 콤마`,`를 사용합니다.

In [72]:
my_tuple = (1, 3.14, "Julia")

(1, 3.14, "Julia")

여기서 우리는 세가지 값을 가지는 튜플을 만들었습니다. 각각의 값은 다른 타입입니다. 우리는 인덱싱을 통해 그 값에 접근할 수 있습니다. 다음과 같이 말이죠.

In [73]:
my_tuple[2]

3.14

우리는 또한 `for`키워드를 통해 튜플 값을 순환할 수 있습니다. 또한 튜플에 함수를 적용 할 수 있습니다. 하지만 우리는 **절대 값을 바꿀 수 없습니다.** 튜플은 불변이기 때문이죠.

섹션 [3.2.4.2]()에서 복수의 값을 반환한 것을 기억하나요? 그러면 우리의 `add_multiply` 함수가 어떤 것을 반환 했는지 조사해 보죠.

In [74]:
return_multiple = add_multiply(1, 2)
typeof(return_multiple)

Tuple{Int64, Int64}

이것은 `return a, b`는 `return (a, b)`와 같기 때문입니다.

In [75]:
1, 2

(1, 2)

이제 왜 이것이 연관되어 있는지 알 수 있을 겁니다.

한가지 튜플에 대해 더 언급하자면, **당신이 하나 이상의 변수를 익명 함수(annonymous function)에 전달하고자 하면, 무엇을 사용해야 할까요? 다신 한번: 튜플입니다!**

In [76]:
map((x, y) -> x^y, 2, 3)

8

또는 둘 이상의 인수도 가능합니다.

In [77]:
map((x, y, z) -> x^y + z, 2, 3, 1)

9

### 3.3.4 네임드 튜플(Named Tuple)

때때로, 우리는 튜플 안에 있는 값에 이름이 있기를 원합니다. 그럴 때 **named tuple** 이 필요한 것입니다. 그들의 기능은 튜플과 상당히 동일 합니다. 그들은 **불변**이고 **어떠한 타입의 값**도 가질 수 있습니다.

네임드 튜플 생성은 튜플과 조금 다릅니다. 괄호`()`와 콤마`,`는 익숙할 겁니다. 하지만 **값의 이름**을 붙여야 합니다.

In [78]:
my_namedtuple = (i=1, f=3.14, s="Julia")

(i = 1, f = 3.14, s = "Julia")

우리는 네임드 튜플의 값을 일반적인 튜플 처럼 인덱싱을 하거나, **이름을 사용해 접근** 할 수 있니다. `.`을 사용해서요.

In [79]:
my_namedtuple.s

"Julia"

네임드 튜플에 대한 이야기를 끝내기 앞서 줄리아 코드를 볼 때 자주 볼 수 있는 한가지 아주 중요한 *짧은* 문법을  소개하겠습니다.종종 줄리아 유저들은 익숙한 괄호`()`와 콤마`,`를 이름 없이 사용합니다. 그렇게 하기 위해서 **네임드 튜플 생성 시작점에 세미콜론`;`을 붙여서 구분합니다.** 이것은 특히 이미 정의된 변수나 너무 긴 라인을 피할 때 유용합니다.

In [80]:
i = 1
f = 3.14
s = "Julia"

my_quick_namedtuple = (; i, f, s)

(i = 1, f = 3.14, s = "Julia")

### 3.3.5 레인지(Ranges)

**레인지**는 줄리아에서 시작과 끝 범위를 표현합니다. 문법은 `start:stop` 형식입니다.

In [81]:
1:10

1:10

보다시피, 생성된 레인지는 `UnitRange{T}` 타입이고 `T`에는 `UnitRange`안에 들어가는 타입입니다.

In [82]:
typeof(1:10)

UnitRange{Int64}

또한, 우리가 모든 값을 모으면 우리는 :

In [83]:
[x for x in 1:10]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

우리는 또한 다른 타입의 레인지도 만들 수 있습니다.

In [84]:
typeof(1.0:10.0)

StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}}

때때로 우리는 기본 인터벌 스텝 크기를 바꾸고자 합니다. 우리는 스텝 사이즈를 집어넣어 `start:step:stop`과 같이 쓸 수 있습니다. 예를 들어 우리가 `Float64` 레인지를 0부터 1까지 0.2 간격으로 만들고자 한다면

In [85]:
0.0:0.2:1.0

0.0:0.2:1.0

만약에 컬렉션으로 레인지를 값으로 변환하고자 한다면, `collect`함수로 할 수 있습니다.

In [86]:
collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

우리는 레인지로 정의된 배열을 얻을 수 있습니다. 배열 이야기가 나왔으니 배열 이야기를 해보죠.

### 3.3.6 배열

기초적인 형태로 **배열(array)** 는 여러 객체를 가질 수 있습니다. 예를 들어 그들은 1차원으로 배열된 여러 수를 가질 수 있습니다.

In [87]:
myarray = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

대부분의 경우 당신은 **성능 이슈로 한가지 타입으로 된 배열**을 원하게 될 것입니다. 하지만, 배열은 다른 타입의 객체를 가질 수 있습니다.

In [88]:
myarray = ["text", 1, :symbol]

3-element Vector{Any}:
  "text"
 1
  :symbol

그들은 데이터 사이언티스트에게 "빵과 버터"입니다. 왜냐하면 배열은 대부분의 **데이터 조작**과 **데이터 시각화** 워크플로우의 근간이 되기 때문입니다.

#### 3.3.6.1 배열 타입

그러면 **배열 타입**부터 시작합니다. 여러가지가 있지만,우리는 데이터 사이언스에서 가장 많이 사용되는 두가지 타입에 집중하겠습니다.

* `Vector{T}`: **일차원** 배열.`Array{T, 1}`
* `Matrix{T}`: **이차원** 배열. `Array{T, 2}`

여기서 `T`는 배열 내 함수 입니다. 예를 들어 `Vector{Int64}`는 `Vector` 의 모든 요소가 `Int64`라는 뜻이고 `Matrix{AbtractFloat}`는 `Matrix`의 모든 요소가 `AbstractFloat`의 하위타입이라는 뜻입니다.

대부분의 경우, 특히 테이블 데이터를 다루고 있을 때 우리는 일차원, 또는 이차원 배열을 사용합니다. 그들 모두 `Array` 타입입니다. 하지만, 우리는 `Vector`나 `Matrix`를 사용하여 좀더 깔끔하고 간결하게 씁니다.

#### 3.3.6.2 배열 생성

어떻게 배열을 **구성**할 수 있을까요? 이 섹션에서 우리는 저수준 방법으로 배열을 만드는 것으로 시작합니다. 이것은 어떤 상황에서 고성능 코드를 만들기 위해 필요합니다. 하지만 대부분의 경우, 이것은 필요하지 않고 우리는 안전하게 좀더 편리한 방법으로 배열을 구성할 수 잇습니다. 그 좀더 변한 방법은 뒷 부분에서 다룹니다.

줄리아 배열에서 저수준 컨스트럭터는 **기본 컨스트럭터**입니다. 이것은 요소 타입을 타이 파라미터로 `{}` 중괄호 안에서 받으며 컨스트럭터 안에서 당신은 원하는 차원과 엘리먼트 타입을 전달 할 수 있습니다. 
정의되지 않은 엘리먼트는 `undef`를 타입 인자로 벡터와 행렬을 생성할 때 사용하는 것은 알반적입니다. 10개의 `undef`, `Float64` 요소를 갖는 벡터를 구성하고자 하면

In [89]:
my_vector = Vector{Float64}(undef, 10)

10-element Vector{Float64}:
 2.54079883541e-312
 2.54079883557e-312
 2.54527789456e-312
 2.540798835886e-312
 2.54527789456e-312
 2.54527789456e-312
 2.540798845847e-312
 2.54079883652e-312
 2.540798836835e-312
 2.542762133323e-312

행렬에서는, 우리가 2차원 객체르르 다루고 있기 때문에, 우리는 두 차원 인자를 전달해야 합니다. 하나는 **행**이고 하나는 **열**입니다. 예를 들어 10개의 행과 2개의 열의 `undef`를 가진 행렬으르 생성한다고 하면

In [90]:
my_matrix = Matrix{Float64}(undef, 10, 2)

10×2 Matrix{Float64}:
 2.54453e-312  2.54497e-312
 2.54082e-312  2.54453e-312
 2.54497e-312  2.54082e-312
 2.54519e-312  9.97338e-313
 2.54519e-312  9.76118e-313
 2.54268e-312  9.33678e-313
 2.54268e-312  1.18832e-312
 2.54453e-312  8.48798e-313
 2.54268e-312  6.36599e-314
 2.54497e-312  2.54086e-312

우리는 **문법 별칭**을 사용해 자주 사용하는 값을 가진 배열을 생성할 수 있습니다.

* `zeros`는 모든 값이 0으로 생성됩니다. 기본 타입은 `Float64`이며 필요하면 바꿀 수 있습니다.

In [91]:
my_vector_zeros = zeros(10)

10-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [92]:
my_matrix_zeros = zeros(Int64, 10, 2)

10×2 Matrix{Int64}:
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0
 0  0

* `ones`는 모든 값을 1로 만든 배열입니다.

In [93]:
my_vector_ones = ones(Int64, 10)

10-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1
 1
 1
 1

In [94]:
my_matrix_ones = ones(10, 2)

10×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0
 1.0  1.0

다른 요소에 대해, 우리는 `undef`로 된 배열을 생성하고, `fill!` 함수를 써서 원하는 값으로 채울 수 있습니다. 여기 `3.14`로 된 예제를 보시죠.

In [95]:
my_matrix_π = Matrix{Float64}(undef, 2, 2)
fill!(my_matrix_π, 3.14)

2×2 Matrix{Float64}:
 3.14  3.14
 3.14  3.14

우리는 **Array literals**로 배열을 생성할 수 있습니다. 여기 2x2 정수 행렬 예제를 보시죠.

In [96]:
[[1 2]
 [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

Array literals는 `[]`앞에 타입지정도 받을 수 있습니다. 도한, 우리가 같은 2x2 배열이지만 실수형을 원한다면, 다음과 같이 할 수 있습니다.

In [97]:
Float64[[1 2]
        [3 4]]

2×2 Matrix{Float64}:
 1.0  2.0
 3.0  4.0

이것은 벡터에서도 작동합니다.

In [98]:
Bool[0, 1, 0, 1]

4-element Vector{Bool}:
 0
 1
 0
 1

여러 arrary literals를 **섞어서** 사용할 수도 있습니다.

In [99]:
[ones(Int, 2, 2), zeros(Int, 2, 2)]

2-element Vector{Matrix{Int64}}:
 [1 1; 1 1]
 [0 0; 0 0]

In [100]:
[zeros(Int, 2, 2)
    ones(Int, 2, 2)]

4×2 Matrix{Int64}:
 0  0
 0  0
 1  1
 1  1

In [101]:
[ones(Int, 2, 2) [1; 2]
    [3 4] 5]

3×3 Matrix{Int64}:
 1  1  1
 1  1  2
 3  4  5

배열을 생성하는 또다른 강력한 방법은 **배열 컴프리핸션**입니다. 이것은 대부분의 경우 더 나은 방법입니다. 이것은 루프, 인덱싱, 그리고 다른 에러에 취약한 연산을 피할 수 있습니다. 당신이 원하는 걸 `[]` 대괄호 안에 지정하면 됩니다. 예를 들면 우리가 1 부터 10까지의 값을 제곱한 행렬을 원한다면

In [102]:
[x^2 for x in 1:10]

10-element Vector{Int64}:
   1
   4
   9
  16
  25
  36
  49
  64
  81
 100

다 변수를 인풋으로 받을 수도 있습니다.

In [103]:
[x*y for x in 1:10 for y in 1:2]

20-element Vector{Int64}:
  1
  2
  2
  4
  3
  6
  4
  8
  5
 10
  6
 12
  7
 14
  8
 16
  9
 18
 10
 20

그리고 조건문도요.

In [104]:
[x^2 for x in 1:10 if isodd(x)]

5-element Vector{Int64}:
  1
  9
 25
 49
 81

array literals와 같이 원하는 타입을 `[]`대괄호 앞에 지정할 수도 있습니다.

In [105]:
Float64[x^2 for x in 1:10 if isodd(x)]

5-element Vector{Float64}:
  1.0
  9.0
 25.0
 49.0
 81.0

마지막으로 우리는 **병합 함수**를 써서 배열을 만들 수 있습니다. 병합(Concatenation)은 컴퓨터 프로그램에서 일반적인 표현으로 "연결한다"는 뜻입니다. 예를 들어 우리는 문자열 "aa"와 "bb"를 병합해 "aabb"를 얻을 수 있습니다.

In [106]:
"aa" * "bb"

"aabb"

또한 우리는 배열들을 병합해 새로운 배열을 만들 수 있습니다.

*`cat`: 특정 차원에 따라 인풋 배열을 병합합니다.

In [107]:
cat(ones(2), zeros(2), dims=1)

4-element Vector{Float64}:
 1.0
 1.0
 0.0
 0.0

In [108]:
cat(ones(2), zeros(2), dims=2)

2×2 Matrix{Float64}:
 1.0  0.0
 1.0  0.0

`vcat`: 수직 병합으로 `cat(...; dims=1)`의 축약형입니다.

In [109]:
vcat(ones(2), zeros(2))

4-element Vector{Float64}:
 1.0
 1.0
 0.0
 0.0

`hcat`: 수평 병합으로 `cat(...; dims=2)`의 축약형 입니다.

In [110]:
hcat(ones(2), zeros(2))

2×2 Matrix{Float64}:
 1.0  0.0
 1.0  0.0

#### 3.3.6.3 배열 살펴보기

일단 배열이 생기면, **살펴보는게** 자연스러운 다음 단계일 것입니다. 어떤 배열이든 살펴볼 수 있는 여러 편리한 함수들이 많이 있습니다.

어떤 **타입의 요소**가 들어가 있는지 아는 것은 아주 유용합니다. 우리는 이것을 `eltype`을 통해서 할 수 있습니다.

In [111]:
eltype(my_matrix_π)

Float64

타입을 알고나면, **배열 차원**이 궁금해질 것입니다. 줄리아는 몇몇 함수가 이를 위해 준비되어 있습니다.

* `length`: 요소의 총 수

In [112]:
length(my_matrix_π)

4

* `ndims`: 차원 수

In [113]:
ndims(my_matrix_π)

2

* `size`: 이것은 약간 절묘합니다. 기본적으로 이것은 배열의 차원을 다은 튜플을 반환합니다.

In [114]:
size(my_matrix_π)

(2, 2)

* 당신은 `size`함수의 두번째 인자로 차원을 지정할 수 있습니다. 여기 두번째 축은 열입니다.

In [115]:
size(my_matrix_π, 2)

2

#### 3.3.6.4 배열 인덱싱 및 슬라이싱

때때로, 우리는 배열의 일부분만 살펴보고 십습니다. 이것을 `인덱싱`과 `슬라이싱`이라고 부릅니다. 당신이 어떤 특정 벡터를 관측하고자 한다면, 또는 행렬의 행이나 열을 보고 싶다고 한다면, 당신은 아마 **배열 인덱싱**이 필요할 겁니다.

우선, 샘플이 될 벡터와 행렬을 만들겠습니다.

In [116]:
my_example_vector = [1, 2, 3, 4, 5]
my_example_matrix = 
   [[1 2 3]
    [4 5 6]
    [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

벡터부터 시작해 봅시다. 당신이 벡터에서 두번재 요소를 원한다고 해봅시다. `[]` 대괄호에 원하는 **인섹스**번호를 넣어서 덧붙이면 됩니다.

In [117]:
my_example_vector[2]

2

같은 문법이 행렬에도 적용됩니다. 단, 행렬은 2차원 배열이기 때문에, 우리는 행과 열을 모두 지정해 주어야 합니다. 그러면 두번째 행(첫번째 차원), 첫번 째 열(두번째 차원) 요소를 꺼내 봅시다.

In [118]:
my_example_matrix[2, 1]

4

줄리아는 또한 **처음**와 **끝**을 나타내는 `begin`과 `end`라는 편리한 키워드가 있습니다. 

예를 들어, 마지막으로부터 두번째 요소를 벡터에서 지정한다면

In [119]:
my_example_vector[end-1]

4

이것은 행렬에도 사용됩니다. 그러면 마지막 행, 두번째 열 요소를 꺼내봅시다.

In [120]:
my_example_matrix[end, begin+1]

8

종종 우리는 한 요소만이 아니라 **요소의 부분집합**이 필요할 때가 있습니다. 우리는 이것을 배열 **슬라이싱**을 통해 해낼 수 있습니다. 이것은 인덱싱 문법과 같습니다. 하지만 추가로 `:` 콜론을 넣어 우리가 자르고자 하는 범주를 정합니다. 예를 들어, 우리가 벡터의 두번째부터 네번째 요소를 원한다면 

In [121]:
my_example_vector[2:4]

3-element Vector{Int64}:
 2
 3
 4

우리는 같은 것을 행렬에서도 할 수 있습니다. 특히, 특정 차원의 **모든 요소**를 선택하고 싶다면 우리는 그저 `:`을 쓰면 됩니다.
예를 들어, 두번째 행의 모든 요소를 선택한다면

In [122]:
my_example_matrix[2, :]

3-element Vector{Int64}:
 4
 5
 6

여러분들은 이것을 "두번째 행을 선택하고 모든 요소를 가져와"와 같이 해석할 수 있습니다.

이것은 또한 `begin`과 `end`를 지원합니다.

In [123]:
my_example_matrix[begin+1:end, end]

2-element Vector{Int64}:
 6
 9

#### 3.3.6.5 배열 조작

배열을 **다루는**데에는 몇가지 방법이 있습니다. 가장 먼저는 **배열의 한 요소**를 바꾸는 것일 겁니다. 우리는 그냥 원하는 요소의 배열 인덱스에 등호`=`를 사용하면 됩니다.

In [124]:
my_example_matrix[2, 2] = 42
my_example_matrix

3×3 Matrix{Int64}:
 1   2  3
 4  42  6
 7   8  9

또는 **배열 요소의 부분집합**을 수정할 수 있습니다. 이경우는 우리는 배열을 잘라 등호`=`로 할당해야 합니다.

In [125]:
my_example_matrix[3, :] = [17, 16, 15]
my_example_matrix

3×3 Matrix{Int64}:
  1   2   3
  4  42   6
 17  16  15

한가지 언급하자면, 우리는 벡터를 할 당해야 합니다. 왜냐하면 잘린 배열이 `Vector`타입이기 때문입니다.

In [126]:
typeof(my_example_matrix[3, :])

Vector{Int64} (alias for Array{Int64, 1})

두 번째 우리가 배열을 다룰 수 잇는 것은 **배열의 모양을 바꾸는 것입니다.** 당신이 6개 요소를 가진 벡터가 있는데 당신은 이것을 3x2행렬로 바꾸고 싶다고 합시다. 당신은 이것을 `reshape`를 가지고 할 수 있습니다. 바꾸고자 하는 배열을 첫 인자로 하고 바꾸고자 하는 차원을 튜플로 한 것을 두번째 인자로 합니다.

In [127]:
six_vector = [1, 2, 3, 4, 5, 6]
three_two_matrix = reshape(six_vector, (3, 2))
three_two_matrix

3×2 Matrix{Int64}:
 1  4
 2  5
 3  6

당신은 이것을 다시 벡터로 바꿀 수 있습니다. 한 가지 차원만 가진 튜플을 두번째 인자로 넘기는 것을 통해 말입니다.

In [128]:
reshape(three_two_matrix, (6,))

6-element Vector{Int64}:
 1
 2
 3
 4
 5
 6

세번째 우리가 하고 싶은 배열 조작은 **함수를 배열 요소 모두에게 적용하는 것입니다.** 여기가 '닷' 연산자 `.`가 등장하는 곳이고 또한 흩뿌리기(*broadcasting*)라고도 합니다.

In [129]:
logarithm.(my_example_matrix)

3×3 Matrix{Float64}:
 0.0      0.693147  1.09861
 1.38629  3.73767   1.79176
 2.83321  2.77259   2.70805

줄리아에서 점 연산자는 아주 다재다능합니다. infix 연산자들에도 사용할 수 있습니다.

In [130]:
my_example_matrix .+ 100

3×3 Matrix{Int64}:
 101  102  103
 104  142  106
 117  116  115

벡터에 대해서 흩뿌리는 대안은 `map`을 사용하는 것입니다.

In [131]:
map(logarithm, my_example_matrix)

3×3 Matrix{Float64}:
 0.0      0.693147  1.09861
 1.38629  3.73767   1.79176
 2.83321  2.77259   2.70805

이것은 상당히 깔끔합니다. 하지만 같은 연산은 다음과 같습니다.

In [132]:
(x -> 3x).(my_example_matrix)

3×3 Matrix{Int64}:
  3    6   9
 12  126  18
 51   48  45

다음으로 `map`은 슬라이싱과 같이 사용됩니다.

In [133]:
map(x -> x+100, my_example_matrix[:, 3])

3-element Vector{Int64}:
 103
 106
 115

마지막으로, 때때로 특히 테이블 형태의 데이터를 다룰 때 우리는 **특정 배열 차원 전체 요소에 함수를 적용하는 것을**원할 때가 있습니다. 
이것은 `mapslices` 함수를 써서 할 수 있습니다. `map`과 같이 첫번째 인자는 함수이고 두번째 인자는 배열 입니다. 유일하게 다른 건 우리는 `dims` 인자를 통해 어떤 차원을 우리가 바꾸고 싶은 요소가 있는지 지정해야 한다는 점입니다.

예를 들어, `mapslices`를 `sum`함수와 같이 써보도록 합시다. 행은`dims=1`, 열은 `dims=2`입니다.

In [134]:
# rows
mapslices(sum, my_example_matrix; dims=1)

1×3 Matrix{Int64}:
 22  60  24

In [135]:
# columns
mapslices(sum, my_example_matrix; dims=2)

3×1 Matrix{Int64}:
  6
 52
 48

#### 3.3.6.6 배열 반복

아주 흔한 연산은 **배열을 `for`루프로 순환하면서 반복하는 것입니다.** 일반적인 `for`루프는 배열을 순환하고 각 요소의 값을 반환합니다.

다음은 벡터를 사용한 가장 간단한 예제입니다.

In [136]:
simple_vector = [1, 2, 3]

empty_vector = Int64[]

for i in simple_vector
    push!(empty_vector, i + 1)
end

empty_vector

3-element Vector{Int64}:
 2
 3
 4

때때로 각 요소를 순환하지 않고 배열 인덱스를 순환하고 싶을 때가 있습니다. **우리는 이 때 `eachindex`함수를 `for`루프와 결합하여 각 배열의 인덱스를 순환할 수 있습니다.**

다시, 벡터로 만든 에제를 보시죠.

In [137]:
forty_twos = [42, 42, 42]

empty_vector = Int64[]

for i in eachindex(forty_twos)
    push!(empty_vector, i)
end

empty_vector

3-element Vector{Int64}:
 1
 2
 3

이 예제에서, `eachinex(forty_twos)`는 `forty_twos`의 인덱스 `[1, 2, 3]`를 반환합니다. 

동일하게 우리는 메트릭스에서도 순환할 수 있습니다. `for`루프는 컬럼을 먼저 순환하고 행을 순환합니다. 먼저 첫번째 컬럼의 첫번째 행 부터 마지막 행까지 순환한 다음에, 두번째 컬럼으로 넘어가서 같은 방식으로 반환하는 것을 마지막 컬럼까지 합니다.

다른 프로그래밍 언어처럼, 줄리아는 많은 과학적 프로그래밍 언어처럼 "컬럼 메이저"입니다. 컬럼 메이저는 컬럼 안에 있는 요소들이 메모리에서 이웃하게 저장된다는 의미입니다 이것은 또한, 컬럼 기반으로 순환하는 것이 행 기반으로 순환하는 것보다 훨씬 빠르다는 뜻입니다.

예제를 통해 보여드리겠습니다.

In [138]:
column_major = [[1 3]
                [2 4]]

row_major = [[1 2]
             [3 4]]

2×2 Matrix{Int64}:
 1  2
 3  4

우리가 컬럼 메이저 순서로 입력된 벡터를 순환하면, 결과는 정렬되어 있습니다.

In [139]:
indexes = Int64[]

for i in column_major
    push!(indexes, i)
end

indexes

4-element Vector{Int64}:
 1
 2
 3
 4

하지만, 다른 행렬에서는 정렬이 되지 않습니다.

In [140]:
indexes = Int64[]

for i in row_major
    push!(indexes, i)
end

indexes

4-element Vector{Int64}:
 1
 3
 2
 4

이런 순환을 위해 특정된 함수를 쓰는 것이 자주 낫습니다.

- `eachcol`: 배열의 열 우선으로 순환

In [141]:
first(eachcol(column_major))

2-element view(::Matrix{Int64}, :, 1) with eltype Int64:
 1
 2

- `eachrow`: 배열의 행부터 순환

In [142]:
first(eachrow(column_major))

2-element view(::Matrix{Int64}, 1, :) with eltype Int64:
 1
 3

### 3.3.7 짝(Pair)

배열에 대한 방대한 내요에 비하면 이 페어에 대한 부분은 간결 합니다.
`Pair`는 **두 객체를 담은 데이터 구조 입니다.**(보통 서로 연관된) 우리는 다음과 같은 문법으로 페어를 정의합니다.

In [143]:
my_pair = "Julia" => 42

"Julia" => 42

요소는 `first`와 `second`에 저장됩니다.

In [144]:
my_pair.first

"Julia"

In [145]:
my_pair.second

42

하지만, 대부분의 경우, `first`와 `last`를 쓰는 것이 간결합니다.

In [146]:
first(my_pair)

"Julia"

In [147]:
last(my_pair)

42

페어는 데이터 처리와 데이터 시각화에 많이 시용됩니다. 왜냐하면 `DataFrames.jl`(섹션 [4]())과 `makie.jl`(섹션 [5]())에서 매인 함수 인자 타입으로 사용하기 때문입니다. 예를 들어 `DataFrames.jl`에서 우리는 `:a => :b`를 보게 될 텐데 이는 컬럼 `:a` 를 `:b`로 이름을 다시 지정하는 것입니다.

### 3.3.9 딕셔너리

`Pair`를 이해하셨다면, `Dict`는 문제가 되지 않습니다. 모든 실용적인 목적에서, `Dict`는 **키를 값으로 맵핑**하는 것입니다. 맵핑한다는 것은, 당신이 `Dict`에 어떤 키 값을 주면, `Dict`은 어떤 값이 속하는지 보여줍니다. `key`와 `value`는 어떤 타입도 가능하지만, 보통 `key`는 문자열입니다.

줄리아에서 `Dict`를 만드는데 두가지 방법이 있습니다. 첫번째는 `(key, value)`형태의 튜플 벡터를 `Dict`생성자에 넣는 것입니다. 

In [148]:
name2number_map = Dict([("one", 1), ("two", 2)])

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

`Pair`타입을 이용해 좀더 읽기 쉬운 문법이 있습니다.`key => value` 모양의 `Pair`를 `Dict` 생성자에 넘길 수 있습니다.

In [149]:
name2number_map = Dict("one" => 1, "two" => 2)

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

`Dict`의 `value`를 `key`를 이용한 인덱싱으로 꺼낼 수 있습니다.

In [150]:
name2number_map["one"]

1

만약 `Dict`에 어떤 `key`가 포함 되어 있는지 확인하고 싶다면, `keys`와 `in`을 쓰면 됩니다.


In [151]:
"two" in keys(name2number_map)

true

`key`를 지우고자 한다면, `delete!`함수를 쓰면 됩니다.

In [152]:
delete!(name2number_map, "three")

Dict{String, Int64} with 2 entries:
  "two" => 2
  "one" => 1

또는 값을 받고 지우고자 한다면, `pop!`을 쓸 수 있습니다.

In [153]:
popped_value = pop!(name2number_map, "two")

2

이제 `name2number_map`은 한가지 `key`만 가지고 있습니다.

In [154]:
name2number_map

Dict{String, Int64} with 1 entry:
  "one" => 1

`Dict`또한 `DataFrames.jl`(섹션 [4]())에서 데이터 조작할 때 사용되며, `Makie.jl`(섹션 [5]())에서 데이터 시각화 할 때 사용됩니다. 그렇기 때문에 기본적인 기능을 아는 것은 중요합니다.

`Dict`를 생성하는데 아주 유용한 또 다른 방법이 있습니다. 당신에게 두 벡터가 있고 당신은 하나는 `key`로 나머지 하나는 `value`가 되도록 `Dict`를 만들고 싶다고 해봅시다. `zip`함수는 두 객체를 "붙여"주어서 이를 해낼 수 있습니다.(지퍼처럼 말이죠)

In [155]:
A = ["one", "two", "three"]
B = [1, 2, 3]

name2number_map = Dict(zip(A, B))

Dict{String, Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

### 3.3.10 심볼

`symbol`은 사실 데이터 구조가 아닙니다. 이것은 타입이고 거의 문자열처럼 행동합니다. 문자를 쌍따옴표로 감싸지 않고, 심볼은 콜론(:)으로 시작합니다. 그리고 언더스코어를 사용할 수 있습니다.

In [156]:
sym = :some_text

:some_text

우리는 심볼을 쉽게 문자열로 바꿀 수 있고 그 반대도 간단합니다.

In [157]:
s = string(sym)

"some_text"

In [158]:
sym = Symbol(s)

:some_text

심볼의 한가지 간단한 장점은 당신은 한 문자를 덜 칠 수 있습니다. `:some_text`와 `some text`를 비교해보세요. 우리는 `Symbol`을 `DataFraes.jl`패키지(섹션 [4]())에서 데이터 조작할 때와 `Makie.jl`패키지(섹션 [5]())에서 데이터 시각화를 할 때 많이 사용합니다. 

### 3.3.11 Splat Operator

줄리아에서 우리는 "Splat" 연산자 `...`를 사용할 수 있습니다. 이것은 함수에서 **인자의 시퀀스**를 부를 때 사용합니다. 우리는 가끔 **데이터 조작*과 **데이터 시각화** 쳅터에서 사용합니다.

splatting을 이깋는 가장 직관적인 방법은 예제를 통하는 것입니다. `add_elements`함수는 3 인자를 함께 더합니다.

In [159]:
add_elements(a, b, c) = a + b + c

add_elements (generic function with 1 method)

이제, 우리는 요소가 3개인 콜렉션이 있다고 합니다. 이를 함수에 전달하는 나이브한 방법은 아래와 같습니다.

In [160]:
my_collection = [1, 2, 3]

add_elements(my_collection[1], my_collection[2], my_collection[3])

6

여기서 우리는 "splat" 연산자 `...`를 사용해서 콜렉션(자주 배열, 벡터, 튜플, 또는 range)를 취해서 이를 인자의 시퀀스로 만들 수 있습니다.

In [161]:
add_elements(my_collection...)

6

`...`은 우리가 변환하고자 하는 콜렉션 뒤에 위치합니다. 위 예제와 아래 예제는 동일합니다.

In [162]:
add_elements(my_collection...) == add_elements(my_collection[1], my_collection[2], my_collection[3])

true

함수를 부를 때 인자에서 splatting 연산자가 있으면 줄리아는 이를 콤마로 나뉘어진 콜랙션의 인자 모두를 인자 시퀀스로 변환시킵니다. 

이것은 또한 range에도 작동합니다.

In [163]:
add_elements(1:3...)

6

## 3.4 파일 시스템

데이터 과학에서, 많은 프로젝트가 협력적 노력을 통해 진행됩니다. 우리는 코드와, 데이터, 테이블, 그림 등을 공유합니다. 
모든 것 뒤에 **운영체제(Operating System, OS)**가 있습니다.
이상적인 세상에선, 같은 프로그램은 **같은** 결과를 **다른** 운영체제에서 낼 것입니다. 불행히도, 항상 그렇지는 않습니다. 한가지 예시로, `/home/john`과 같은 리눅스 경로와 `C:\Users\john`과 같은 윈도우 경로의 차이가 있습니다. 
그렇기 때문에 **파일 시스템 우수 사례**에 대해서 이야기 하는 것이 중요합니다.

줄리아는 **다른 운영 체제간 차이를 다루는** 기본 파일 시스템 능력이 있습니다. 
그거슨 코어`Base` 줄리아 라이브러리에 있는 `Filesystem` 모듈에 있습니다.

CSV, 엑셀파일이나 다른 줄리아 스크립트를 다룰 때, 당신의 코드가 **다른 운영체제 파일시스템에서 돌아가도록** 확인하세요. 이것은 `joinpath`, `@__FILE__`과 `pkgdir` 함수를 통해 간단히 할 수 있습니다.

만약 당신이 당신의 코드를 패키지에서 짤 때, 당신은 `pkgdir`를 사용해서 패키지 루트 디렉토리를 구할 수 있습니다. 예를 들어, 우리가 이 책을 만들 때 사용한 줄리아 데이터 과학 패키지(JDS)의 루트 디렉토리는 

/home/runner/work/JuliaDataScience/JuliaDataScience

입니다.

당신도 보듯이, 이 책은 리눅스 컴퓨터에서 생성되었습니다. 당신이 스크립트를 사용한다면, 그 스크립트 파일의 위치는 아래와 같이 구할 수 있습니다.

In [165]:
root = dirname(@__FILE__)

""

위 두 명령어의 장점은, 그들은 어떻게 유저들이 줄리아를 시작했는지에 대해 독립적이라는 점입니다. 다른 말로 하자면, 유저가 프로그램을 시작할 때 `julia scripts/script.jl`이나 `julia script.jl`의 경로 모두가 같다는 뜻입니다.

다음 단계는 `root`에서 우리가 원하는 파일이 있는 상대 경로를 포함하는 것입니다. 다른 OS는 하위 폴더의 상대 경로를 구축하는 다른 방식을 따르기 때문에(어떤 것은 슬레시를 사용하고`/` 어떤 것은 백슬레시`\`를 사용합니다.) 우리는 그냥 파일 상대 경로를 `root`문자열에 합칠 수 없습니다. 그러기 위해서 ` joinpath` 함수가 있습니다. 이것은 사용하고 있는 OS 파일시스템에 맞는 방식으로 상대 경로를 병합합니다.

예를 들어 `my_script.jl`라고 하는 스크립트가 당신의 프로젝트 디렉토리에 있다고 합시다. 당신은 `my_script.jl`의 로부스트한 파일 경로 표현을 다음과 같이 구할 수 있습니다.

In [166]:
joinpath(root, "my_script.jl")

"my_script.jl"

`joinpath`는 또한 **하위 폴더**를 다룰 수 있습니다. 당신의 폴더 이름이 `data/`를 당신의 프로젝트의 하위 폴더로 가지고 있다는 아주 일반적인 상황을 상상해 봅시다. 당신의 폴더 안에는 `my_data.csv`라고 하는 CSV 파일이 있습니다. 당신은 `my_data.csv`의 같은 로부스트한 파일 경로 표현을 다음과 같이 구할 수 있습니다. 

In [167]:
joinpath(root, "data", "my_data.csv")

"data/my_data.csv"

이것은 챙길만한 좋은 습관입니다. 왜냐하면 다른 사람들에게 발생할 수 도 있는 많은 문제를 예방할 수 있기 때문입니다.

## 3.5 줄리아 기본 라이브러리

줄리아는 모든 줄리아 인스톨과 함께 사용가능한 **풍부한 기본 라이브러리**을 가지고 있습니다.
지금까지 본 타입, 데이터 구조, 파일시스템과 다르게, 특정 모듈이나 함수를 쓰기 위해서는 **반드시 당신의 환경에 기본 라이브러리 모듈을 불러와야 합니다.**

이것은 `using`이나 `import`를 통해 가능합니다. 이 책에서, 우리는 `using`을 통해 코드를 불러오고자 합니다.

```julia
using ModuleName
```

이렇게 한 다음에는, `ModuleName`안에 있는 모든 함수와 타입에 접근 할 수 있습니다.

### 3.5.1 Dates

어떻게 날자와 타입스탬프를 다루는지 아는 건 데이터 과학에서 중요합니다. 우리가 *왜 줄리아입니까?*(섹션 [2]())에서 이야기 했듯이, 파이썬의 `pandas`는 자신만의 `datetime` 타입을 사용합니다. 
이런 방식은 R의 tidyverse의 `lubridate`패키지에서도 동일하게, 자신의 `datetime`을 만들어서 날자들을 처리합니다. 줄리아 패키지는 자신만의 날자 로직을 만들 필요가 없습니다. 왜냐하면 줄리아는 `Dates`라고 하는 기본 라이브러리가 있기 때문입니다.

시작하기 위해서, `Dates` 모듈을 불러옵시다.

In [168]:
using Dates

#### 3.5.1.1 `Date`와 `DateTime` 타입

`Dates` 기본 라이브러리 모듈은 **날자를 다루기 위해 두 타입**을 가지고 있습니다.

1. `Date`: 일자에 관한 시간을 표현합니다.
2. `DateTime`: 밀리세컨드 정확도로 시간을 표현합니다.

우리는 `Date`와 `DateTime`을 기본 생성자를 통해 만들 수 있습니다. 정수형을 통해 연도, 월, 일, 시 등등을 지정합니다.

In [169]:
Date(1987) # year

1987-01-01

In [171]:
Date(1987, 9) # year, month

1987-09-01

In [172]:
Date(1987, 9, 13) # year, month, day

1987-09-13

In [173]:
DateTime(1987, 9, 13, 21) # year, month, day, hour

1987-09-13T21:00:00

In [174]:
DateTime(1987, 9, 13, 21, 21) # year, month, day, hour, minute

1987-09-13T21:21:00

궁금한 사람이 있을 것 같아 말씀드리지만, 1987년 9월 13일, 21:21은 첫 저자인 Jose의 공식 탄생시간입니다.

우리는 또한 `Period`타입을 인자로 줄 수 있습니다.
컴퓨터에게 `Period` **타입은 인간-동등 시간 표현**입니다. 줄리아의 `Dates`는 다음과 같은 `Period` 추상 하위 타입을 가지고 있습니다.

In [175]:
subtypes(Period)

2-element Vector{Any}:
 DatePeriod
 TimePeriod

이것들은 다음과 같은 구체 타입으로 나뉘어지며, 그들은 보면 이해가 가능한(self-explanatory) 것들입니다.

In [176]:
subtypes(DatePeriod)

5-element Vector{Any}:
 Day
 Month
 Quarter
 Week
 Year

In [177]:
subtypes(TimePeriod)

6-element Vector{Any}:
 Hour
 Microsecond
 Millisecond
 Minute
 Nanosecond
 Second

그래서 우리는 대안적으로 Jose의 공식 탄생시간을 다음과 같이 생성할 수 있습니다.

In [178]:
DateTime(Year(1987), Month(9), Day(13), Hour(21), Minute(21))

1987-09-13T21:21:00

#### 3.5.1.2 날자 파싱

대부분의 경우, 우리는 `Date`나 `DateTime` 객체를 바닥부터 만들진 않습니다. 사실 우리는 아마 **문자열을 파싱해서 `Date`나 `DateTime` 타입을 만들 겁니다.**

`Date`와 `DateTime` 생성자는 포맷을 갖춘 문자열을 받을 수 있습니다. 예를 들어, 문자열 1987년 9월 13일을 의미하는`19870913`은 다음과 같이 파싱될 수 있습니다.

In [179]:
Date("19870913", "yyyymmdd")

1987-09-13

눈치챘겠지만, 두번째 인자는 포맷을 나타내고 있습니다. 우리는 첫 네자리가 연도`y`를 나타내고 다음 두자리는 월 `m` 그리고 마지막 두 자리는 일 `d`을 나타내고 있습니다.

이것은 `DateTime`의 타임스탬프에도 적용됩니다.

In [180]:
DateTime("1987-09-13T21:21:00", "yyyy-mm-ddTHH:MM:SS")

1987-09-13T21:21:00

[줄리아 `Dates` 문서]()에서 어떻게 날자 포맷을 정할 수 있는지 더 많은 것들을 찾아 볼 수 있습니다. 매번 찾아보러 가게 되도 너무 우울해 하지 마세요. 우리도 날자와 시간을 다룰 때 그렇게 합니다. 

[줄리아 `Dates` 문서]()에 따르면, `Date(date_string, format_string)`방법을 사용하는 것은 몇번만 불리울 때만 괜찮다고 합니다. 만약 비슷하게 포맷된 많은 날자 문자열을 파싱하려고 한다면, 우선 `DateFormat`타입을 생성하고, 이것을 포맷 문자열 대신 전달하는 것이 훨씬 효과적이라고 합니다. 그러면, 우리 이전 예제는

In [181]:
format = DateFormat("yyyymmdd")
Date("19870913", format)

1987-09-13

대안적으로, 성능의 손실 없이, 당신은 string literal prefix `dateformat"..."`을 사용할 수 있습니다.

In [182]:
Date("19870913", dateformat"yyyymmdd")

1987-09-13